### 比較樣本之 set of objects
- 比較各樣本錄製出 set of objects 的數量
- 比較所需 object regex 的數量

In [1]:
import re
import os
from os import listdir
from os.path import isfile, join
from pathlib import Path
import pandas as pd
from typing import Dict, List, get_type_hints
from IPython.display import display

In [9]:
# 存放 ste of objects 的目錄 C scroing\outputfolder\baseline_Dofloo_26d.csv
path = '../../C scroing/outputfolder/'

def get_all_filenames(dir: str='./') -> list:
    ''' traverse root directory, and list directories as dirs and files as files. Return filenames in rootdir. '''
    files = [f for f in listdir(dir) if isfile(join(dir, f))]
    files.sort()
    return files
dofloo_object_names = [f for f in get_all_filenames(path) if f.startswith('baseline_Dofloo')] # 只選擇這個家族的報告
dofloo_object_dfs = [pd.read_csv(f"{path}{f}") for f in dofloo_object_names]
lenx = len(dofloo_object_names)
print('num of samples', len(dofloo_object_dfs), ', front 3 are:', dofloo_object_names[:3])

num of samples 14 , front 3 are: ['baseline_Dofloo_004.csv', 'baseline_Dofloo_121.csv', 'baseline_Dofloo_26d.csv']

In [25]:
# clean .so linking file
for i in range(lenx):
    df = dofloo_object_dfs[i]
    # dofloo_object_dfs[i].drop(dofloo_object_dfs[i][df.isnull().sum(axis=0) > max_number_of_nans], axis=1)
    # df.drop(list(df.filter(regex = 'so|prober')), axis = 1, inplace = True) # 這只會drop欄位名稱
    df = df[(df["text"].str.contains(".so")==False) & (df["text"].str.contains("prober")==False)]
    # dofloo_object_dfs[i] = d[(d['text'].find('.so') == -1) & (d['text'].find('/prober') == -1) ] # 會噴錯
    dofloo_object_dfs[i] = df
dofloo_object_dfs[9]

                              text   type  weight
0                     /dev/urandom   file       1
1                   /etc/host.conf   file       1
2                       /etc/hosts   file       1
3           /etc/init.d/boot.local   file       2
6               /etc/nsswitch.conf   file       1
7               /etc/rc.d/rc.local   file       2
8                    /etc/rc.local   file       2
20                   /proc/net/dev   file       1
21                  /proc/self/exe   file       1
22                      /proc/stat   file       1
23  /sys/devices/system/cpu/online   file       1
24                               2   file       1
25                             nul   file       1
26                           stdin   file       2
27                    0.0.0.0:1020    net       2
28                   127.0.0.53:53    net       2
29              218.60.25.91:10210    net       2
30                             NIC    net       1
31                           uname  other       1

In [30]:
# num of objects per sample
column_name = [f"S{i+1}" for i in range(lenx)] # S1 ~ S14
sample_name = [filename.split('.')[0].split('_')[2] for filename in dofloo_object_names]
num_of_object = [len(df) for df in dofloo_object_dfs]

summery = pd.DataFrame([sample_name, num_of_object], columns=column_name)
summery.to_csv('比較樣本.csv', index=False) # 沒事不要覆寫!!
summery

    S1   S2   S3   S4   S5   S6   S7   S8   S9  S10  S11  S12  S13  S14
0  004  121  26d  392  44d  52f  54a  570  60f  74e  884  9a3  bd6  f47
1   11   11   11   11   11   11   11   12   19   19    9   11   11   11